version: '3'

services:
  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./BACKEND
      dockerfile: Dockerfile
    ports:
      - "8070:8070"
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
